### ISSUE TITLE
Screen orientation issue

### ISSUE THREAD

**Issue by G93-7** [portari/MediaPipeUnityPlugin_PoseSampleGPU_Android#1]
I have run the PoseSampleGPU project on Android. Pose tracking works fine but I think the app incorrectly responds to screen orientation changes. For example, In portrait mode it is correct but as the orientation changes to landscape mode, it seems that the image and annotations remain in portrait mode and the image does not cover the whole screen. I attach the screenshots taken in every of the four screen orientation modes. 
I think It is possible to correct the image and annotations orientation from the script in each case of screen orientations but I am interested if there is another way. Thank you in advance!

Portrait
![Portrait](https://user-images.githubusercontent.com/80401198/194772879-20fa990e-d777-4abb-90ce-0cadadc5dc89.png)

PortraitUpsideDown
![PortraitUpsideDown](https://user-images.githubusercontent.com/80401198/194772892-a0fb6288-745c-4a50-ad90-92183a5bb73f.png)

LandscapeRight
![LandscapeRight](https://user-images.githubusercontent.com/80401198/194772908-52af914a-d7d4-45c4-a1ff-f8155dff1804.png)

LandscapeLeft
![LandscapeLeft](https://user-images.githubusercontent.com/80401198/194772911-dae7dd0d-0593-4a8b-9442-91caf8391460.png)

**Comment by portari** [comment]
Hi @G93-7. I didn't create the orientation functions in Unity3D because, in my project that I needed to do the tracking, the camera is fixed on a tripod in a single position. You can implement the recognition and orientation adjustment functions according to what Android informs and adapt the Screen rotation in Canvas and AnnotationPoints. I'll be happy to complete the project, if I can, and I'll update with due credits.. Unfortunately, at the moment I cannot implement them due to project deadlines. Thanks to the issue.
